### PR TITLE
Complete Responsive website project, Submitted for review

### PR DESCRIPTION
**Pull request by mkezfarias**
Hello, I'm submitting my responisve website project for review, thank you!

I'm currently unpartnered, Willow from student success authorized me to work solo on this project.

Have a great day 👯‍♂

### CODE REVIEW

**Comment by mkezfarias** [comment]
Sticker checks passed

**Comment by shshamim63** [comment]
### Changes Required!
Hi @mkezmkez  :wave:
Tremendous job on this project. It consists well documented readme, separated files and almost clone of the tnw webpage. 
But there are some issues you need to fix to declare this project as complete.
Please follow the instruction below to make this project complete.:point_down:
___
#### Mandatory Change:
##### 1. Why there is a node_module file in your project? you have to add it in your gitignore.
##### 2. Medium window:
.. It should aligns 3 articles per row in the latest news section
latestnews

.. Categories (Apps, GERA, Tech, etc) section, should hold 2 category boxes per row.
--->Original one
priginalappgear
---> This project 
thisprojectappgear
##### 3. Need to fix the alignment of this section.
--->Original one
originallatestfunding
---> This project 
latestfunding

##### Please submit another code review request after fixing those issues. 
## <em>Happy Coding</em> 
 [Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Comment by mkezfarias** [comment]
Requested changes have been completed

**Comment by suretrust** [comment]
Hello @mkezmkez,

Great job! :ok_hand: **Let's get this merged!** :tada: 

Note: Don't forget to close [this issue](https://github.com/mkezmkez/responsive-design/issues/2)

**Happy coding!**

**Comment by mkezfarias** [comment]
Thank you

**Pull request merged**
